export const ART_TECHNIQUES = {
  // ============ 색칠/드로잉 기본 ============
  COLORING: {
    id: 'COLORING',
    name: 'Coloring',
    nameKo: '색칠하기',
    description: 'Fill in outlines with colors to develop color sense and fine motor skills',
    descriptionKo: '다양한 도안에 색을 채워 색감 감각과 소근육을 발달시킵니다',
    icon: 'Palette',
    category: 'basic',
    difficulty: [1, 2, 3, 4, 5],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 10, max: 30 },
    skills: ['색 인지', '소근육 발달', '집중력', '창의력', '색 조화'],
    materials: ['색연필', '크레파스', '마커', '물감', '파스텔'],
    tips: [
      '테두리 안에서 시작하기',
      '밝은 색부터 어두운 색 순서로',
      '한 방향으로 일정하게 칠하기',
      '빈틈 없이 꼼꼼하게 채우기'
    ],
    variations: ['그라데이션 색칠', '색상환 활용', '무드 컬러링', '계절 색채'],
    credits: 1
  },
  LINE_DRAWING: {
    id: 'LINE_DRAWING',
    name: 'Line Tracing',
    nameKo: '선 따라 그리기',
    description: 'Trace dotted or guide lines to improve hand stability',
    descriptionKo: '점선이나 가이드 선을 따라 그려 손의 안정성을 키웁니다',
    icon: 'Pencil',
    category: 'basic',
    difficulty: [1, 2, 3],
    ageGroups: ['TODDLER', 'LOWER_ELEM'],
    estimatedTime: { min: 5, max: 15 },
    skills: ['손 협응력', '집중력', '기초 드로잉', '선 조절'],
    materials: ['연필', '펜', '크레파스'],
    tips: [
      '천천히 선을 따라가기',
      '손목이 아닌 팔 전체로 움직이기',
      '시작점과 끝점 확인하기'
    ],
    variations: ['직선 연습', '곡선 연습', '지그재그', '나선형'],
    credits: 1
  },
  DOT_CONNECT: {
    id: 'DOT_CONNECT',
    name: 'Dot-to-Dot',
    nameKo: '점잇기',
    description: 'Connect numbered dots to reveal hidden pictures',
    descriptionKo: '번호 순서대로 점을 이어 숨겨진 그림을 완성합니다',
    icon: 'GitBranch',
    category: 'basic',
    difficulty: [1, 2, 3],
    ageGroups: ['TODDLER', 'LOWER_ELEM'],
    estimatedTime: { min: 5, max: 20 },
    skills: ['숫자 인식', '순서 개념', '집중력', '소근육'],
    materials: ['연필', '펜'],
    tips: [
      '숫자 순서대로 연결하기',
      '다음 숫자를 미리 찾아두기',
      '완성 후 색칠하기'
    ],
    variations: ['숫자 점잇기', '알파벳 점잇기', '한글 점잇기', '건너뛰기 점잇기'],
    credits: 1
  },
  SYMMETRY: {
    id: 'SYMMETRY',
    name: 'Symmetry Drawing',
    nameKo: '대칭 그리기',
    description: 'Complete the other half of a symmetrical image',
    descriptionKo: '반쪽 그림을 보고 나머지 반쪽을 그려 대칭 개념을 익힙니다',
    icon: 'FlipHorizontal',
    category: 'drawing',
    difficulty: [2, 3, 4],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 10, max: 25 },
    skills: ['공간 인지', '수학적 사고', '관찰력', '비례감'],
    materials: ['연필', '자', '거울 (선택)'],
    tips: [
      '주요 점들의 위치 먼저 찍기',
      '중심선 기준으로 거리 측정하기',
      '거울로 확인해보기'
    ],
    variations: ['수직 대칭', '수평 대칭', '회전 대칭', '복합 대칭'],
    credits: 1
  },
  MIRROR: {
    id: 'MIRROR',
    name: 'Mirror Drawing',
    nameKo: '거울 그리기',
    description: 'Draw the mirror reflection of an image',
    descriptionKo: '이미지의 거울 반사를 그려 좌우 개념을 익힙니다',
    icon: 'FlipHorizontal2',
    category: 'drawing',
    difficulty: [2, 3, 4],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 10, max: 20 },
    skills: ['공간 지각', '좌우 인식', '집중력'],
    materials: ['연필', '거울'],
    tips: ['원본과 반대 방향으로 그리기', '핵심 포인트 먼저 잡기'],
    variations: ['단순 거울', '복잡한 패턴 거울'],
    credits: 1
  },
  GRID_COPY: {
    id: 'GRID_COPY',
    name: 'Grid Copy',
    nameKo: '칸 옮기기',
    description: 'Copy an image by transferring it grid by grid',
    descriptionKo: '격자를 이용해 그림을 정확하게 옮겨 그립니다',
    icon: 'Grid3x3',
    category: 'drawing',
    difficulty: [2, 3, 4, 5],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 15, max: 40 },
    skills: ['관찰력', '비례감', '정확성', '인내심'],
    materials: ['연필', '자', '지우개'],
    tips: [
      '한 칸씩 집중해서 그리기',
      '선이 지나는 위치 확인하기',
      '전체 형태 수시로 확인'
    ],
    variations: ['동일 크기 복사', '확대 복사', '축소 복사'],
    credits: 1
  },
  ORIGAMI: {
    id: 'ORIGAMI',
    name: 'Origami',
    nameKo: '종이접기',
    description: 'Follow fold lines to create 3D paper art',
    descriptionKo: '전개도와 접기 가이드를 보고 입체 작품을 만듭니다',
    icon: 'FoldVertical',
    category: 'craft',
    difficulty: [1, 2, 3, 4, 5],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 10, max: 45 },
    skills: ['공간 지각력', '순서 이해', '소근육 발달', '집중력', '정교함'],
    materials: ['색종이', '종이', '풀 (일부)'],
    tips: [
      '모서리와 모서리를 정확히 맞추기',
      '접은 선을 손톱으로 꾹 누르기',
      '순서대로 차근차근 접기',
      '어려우면 큰 종이로 연습'
    ],
    variations: ['전통 종이접기', '모듈러 오리가미', '액션 오리가미', '3D 오리가미'],
    credits: 1
  },
  PAPER_CRAFT: {
    id: 'PAPER_CRAFT',
    name: 'Paper Craft',
    nameKo: '종이 공예',
    description: 'Cut, fold, and assemble paper to create crafts',
    descriptionKo: '종이를 오리고 붙여 다양한 작품을 만듭니다',
    icon: 'Scissors',
    category: 'craft',
    difficulty: [2, 3, 4, 5],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 20, max: 60 },
    skills: ['계획력', '공간 구성', '창의력', '조립 능력'],
    materials: ['가위', '풀', '색종이', '도화지', '테이프'],
    tips: [
      '오릴 때 종이를 돌리며 자르기',
      '순서대로 조립하기',
      '풀은 가장자리에만 적당히'
    ],
    variations: ['상자 만들기', '동물 피규어', '건축물', '탈것'],
    credits: 2
  },
  CUTTING: {
    id: 'CUTTING',
    name: 'Cutting Practice',
    nameKo: '오리기',
    description: 'Practice cutting various shapes with scissors',
    descriptionKo: '다양한 모양을 가위로 오려 소근육을 발달시킵니다',
    icon: 'Scissors',
    category: 'craft',
    difficulty: [1, 2, 3],
    ageGroups: ['TODDLER', 'LOWER_ELEM'],
    estimatedTime: { min: 10, max: 20 },
    skills: ['소근육 발달', '손-눈 협응', '집중력', '안전 의식'],
    materials: ['안전 가위', '종이'],
    tips: [
      '곡선은 천천히 종이를 돌리며',
      '엄지는 위로, 손목은 고정',
      '안전하게 가위 사용하기'
    ],
    variations: ['직선 오리기', '곡선 오리기', '도형 오리기', '패턴 오리기'],
    credits: 1
  },
  POPUP: {
    id: 'POPUP',
    name: 'Pop-up Card',
    nameKo: '팝업 카드',
    description: 'Create cards with 3D pop-up elements',
    descriptionKo: '입체적으로 튀어나오는 카드를 만듭니다',
    icon: 'Layers',
    category: 'craft',
    difficulty: [3, 4, 5],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 25, max: 50 },
    skills: ['입체 사고', '계획력', '정밀 작업', '창의력'],
    materials: ['도화지', '가위', '풀', '색칠 도구', '자'],
    tips: [
      '접히는 방향 주의하기',
      '풀은 적당량만 사용',
      '카드를 닫았을 때 확인'
    ],
    variations: ['V-폴드', '박스 팝업', '레이어드', '360도 팝업'],
    credits: 2
  },
  MOBILE: {
    id: 'MOBILE',
    name: 'Mobile',
    nameKo: '모빌',
    description: 'Create hanging mobile decorations',
    descriptionKo: '매달아 움직이는 모빌 장식을 만듭니다',
    icon: 'Wind',
    category: 'craft',
    difficulty: [2, 3, 4],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 30, max: 60 },
    skills: ['균형감', '공간 구성', '창의력'],
    materials: ['도화지', '실', '막대', '가위', '펀치'],
    tips: ['무게 균형 맞추기', '실 길이 조절하기'],
    variations: ['행성 모빌', '동물 모빌', '계절 모빌'],
    credits: 2
  },
  COLLAGE: {
    id: 'COLLAGE',
    name: 'Collage',
    nameKo: '콜라주',
    description: 'Combine various materials to create compositions',
    descriptionKo: '다양한 재료를 조합하여 작품을 구성합니다',
    icon: 'LayoutGrid',
    category: 'mixed',
    difficulty: [2, 3, 4],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 20, max: 45 },
    skills: ['구성력', '창의력', '재료 탐색', '심미감'],
    materials: ['잡지', '색종이', '천', '풀', '가위'],
    tips: [
      '먼저 배치해보고 붙이기',
      '다양한 질감 활용하기',
      '레이어 순서 생각하기'
    ],
    variations: ['잡지 콜라주', '찢어 붙이기', '자연물 콜라주', '사진 콜라주'],
    credits: 1
  },
  STENCIL: {
    id: 'STENCIL',
    name: 'Stencil Art',
    nameKo: '스텐실/판화',
    description: 'Use stencils to create repeated patterns or images',
    descriptionKo: '틀을 이용해 반복 패턴이나 이미지를 만듭니다',
    icon: 'Copy',
    category: 'mixed',
    difficulty: [2, 3, 4],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 15, max: 35 },
    skills: ['패턴 인식', '계획력', '인쇄 원리 이해'],
    materials: ['스텐실 틀', '스펀지', '물감', '마스킹 테이프'],
    tips: [
      '물감은 적게, 여러 번 두드리기',
      '틀을 고정하고 작업하기',
      '건조 후 틀 제거'
    ],
    variations: ['다층 스텐실', '그라데이션', '반복 패턴'],
    credits: 1
  },
  STAMP: {
    id: 'STAMP',
    name: 'Stamping',
    nameKo: '도장 찍기',
    description: 'Use stamps to create patterns and compositions',
    descriptionKo: '다양한 도장을 활용해 패턴과 그림을 만듭니다',
    icon: 'Stamp',
    category: 'mixed',
    difficulty: [1, 2, 3],
    ageGroups: ['TODDLER', 'LOWER_ELEM'],
    estimatedTime: { min: 10, max: 25 },
    skills: ['소근육 발달', '패턴 인식', '창의력', '리듬감'],
    materials: ['도장', '잉크패드', '종이'],
    tips: ['고르게 누르기', '떼기 전 잠시 기다리기', '잉크 양 조절하기'],
    variations: ['자유 찍기', '패턴 만들기', '그림 완성하기'],
    credits: 1
  },
  RUBBING: {
    id: 'RUBBING',
    name: 'Frottage/Rubbing',
    nameKo: '프로타주',
    description: 'Create texture impressions by rubbing',
    descriptionKo: '울퉁불퉁한 표면 위에 종이를 대고 문질러 질감을 표현합니다',
    icon: 'Fingerprint',
    category: 'mixed',
    difficulty: [1, 2, 3],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 10, max: 25 },
    skills: ['질감 탐색', '관찰력', '창의력'],
    materials: ['크레파스', '연필', '얇은 종이', '다양한 표면'],
    tips: ['크레파스를 눕혀서 문지르기', '종이가 움직이지 않게 고정'],
    variations: ['동전 프로타주', '나뭇잎 프로타주', '조합 프로타주'],
    credits: 1
  },
  MARBLING: {
    id: 'MARBLING',
    name: 'Marbling Template',
    nameKo: '마블링 템플릿',
    description: 'Create marbling effect designs',
    descriptionKo: '마블링 효과를 내는 디자인을 만듭니다',
    icon: 'Waves',
    category: 'mixed',
    difficulty: [2, 3, 4],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 15, max: 30 },
    skills: ['색 혼합', '우연성 활용', '창의력'],
    materials: ['마블링 물감', '물', '종이', '막대'],
    tips: ['물감 양 조절하기', '천천히 섞기'],
    variations: ['전통 마블링', '쉐이빙크림 마블링'],
    credits: 1
  },
  MOSAIC: {
    id: 'MOSAIC',
    name: 'Mosaic',
    nameKo: '모자이크',
    description: 'Arrange small pieces to complete larger images',
    descriptionKo: '작은 조각들을 붙여 큰 그림을 완성합니다',
    icon: 'Grid3x3',
    category: 'pattern',
    difficulty: [2, 3, 4],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 25, max: 50 },
    skills: ['인내심', '색 조합', '계획력', '집중력'],
    materials: ['색종이 조각', '풀', '도안', '핀셋 (선택)'],
    tips: ['테두리부터 채우기', '색상 계획 먼저 세우기', '조각 크기 일정하게'],
    variations: ['종이 모자이크', '스티커 모자이크', '비즈 모자이크'],
    credits: 1
  },
  MANDALA: {
    id: 'MANDALA',
    name: 'Mandala',
    nameKo: '만다라',
    description: 'Color radially symmetric mandala patterns',
    descriptionKo: '중심에서 방사형으로 퍼지는 대칭 패턴을 색칠합니다',
    icon: 'Circle',
    category: 'pattern',
    difficulty: [2, 3, 4, 5],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 20, max: 60 },
    skills: ['집중력', '인내심', '색 조화', '안정감', '마음 챙김'],
    materials: ['색연필', '펜', '마커', '젤펜'],
    tips: ['중심부터 바깥으로', '같은 모양은 같은 색으로', '색상 조화 생각하기'],
    variations: ['기하학 만다라', '자연 만다라', '동물 만다라', '꽃 만다라'],
    credits: 1
  },
  ZENTANGLE: {
    id: 'ZENTANGLE',
    name: 'Zentangle',
    nameKo: '젠탱글',
    description: 'Create structured patterns using repetitive strokes',
    descriptionKo: '반복적인 선으로 구조화된 패턴을 만듭니다',
    icon: 'Waves',
    category: 'pattern',
    difficulty: [3, 4, 5],
    ageGroups: ['UPPER_ELEM'],
    estimatedTime: { min: 20, max: 45 },
    skills: ['집중력', '패턴 인식', '창의력', '마음 챙김'],
    materials: ['펜', '연필', '종이'],
    tips: ['선 하나에 집중하기', '실수해도 괜찮아요', '반복이 핵심'],
    variations: ['기본 젠탱글', '동물 젠탱글', '글자 젠탱글'],
    credits: 1
  },
  DOODLE: {
    id: 'DOODLE',
    name: 'Doodling',
    nameKo: '두들링',
    description: 'Free-form drawing and pattern making',
    descriptionKo: '자유롭게 낙서하며 패턴을 만듭니다',
    icon: 'Pen',
    category: 'pattern',
    difficulty: [1, 2, 3, 4],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 10, max: 30 },
    skills: ['창의력', '자유로운 표현', '상상력'],
    materials: ['펜', '마커', '종이'],
    tips: ['마음 가는대로 그리기', '빈 공간 채우기', '연결해서 그리기'],
    variations: ['자유 두들', '테마 두들', '연속 두들'],
    credits: 1
  },
  PATTERN: {
    id: 'PATTERN',
    name: 'Pattern Practice',
    nameKo: '패턴 연습',
    description: 'Learn to recognize and create repeating patterns',
    descriptionKo: '규칙적인 무늬를 따라 그리고 만들어 패턴 감각을 키웁니다',
    icon: 'Repeat',
    category: 'pattern',
    difficulty: [1, 2, 3, 4],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 10, max: 25 },
    skills: ['규칙 인식', '수학적 사고', '예측력', '논리력'],
    materials: ['연필', '펜', '색연필'],
    tips: ['반복 단위를 먼저 파악하기', '규칙을 말로 설명해보기', '다음 것 예측해보기'],
    variations: ['AB 패턴', 'ABC 패턴', '성장 패턴', '복합 패턴'],
    credits: 1
  },
  BORDER: {
    id: 'BORDER',
    name: 'Border Design',
    nameKo: '테두리 꾸미기',
    description: 'Design decorative borders and frames',
    descriptionKo: '장식적인 테두리와 프레임을 디자인합니다',
    icon: 'Square',
    category: 'pattern',
    difficulty: [1, 2, 3],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 10, max: 25 },
    skills: ['장식 감각', '반복 패턴', '디자인'],
    materials: ['펜', '색연필', '마커'],
    tips: ['코너 먼저 디자인하기', '반복 단위 정하기'],
    variations: ['기하학 테두리', '자연 테두리', '캐릭터 테두리'],
    credits: 1
  },
  PROPORTION: {
    id: 'PROPORTION',
    name: 'Proportion Drawing',
    nameKo: '비례 그리기',
    description: 'Learn to draw objects in correct proportions',
    descriptionKo: '사물의 비례를 맞춰 그리는 연습을 합니다',
    icon: 'Scale',
    category: 'advanced',
    difficulty: [3, 4, 5],
    ageGroups: ['UPPER_ELEM'],
    estimatedTime: { min: 15, max: 35 },
    skills: ['관찰력', '비례감', '측정 능력'],
    materials: ['연필', '자', '지우개'],
    tips: ['기준점 잡기', '비교하며 그리기', '자로 확인하기'],
    variations: ['얼굴 비례', '인체 비례', '사물 비례'],
    credits: 1
  },
  PERSPECTIVE: {
    id: 'PERSPECTIVE',
    name: 'Perspective',
    nameKo: '원근법',
    description: 'Learn to draw with depth and perspective',
    descriptionKo: '가까운 것과 먼 것의 크기 차이를 표현하는 법을 배웁니다',
    icon: 'Move3d',
    category: 'advanced',
    difficulty: [4, 5],
    ageGroups: ['UPPER_ELEM'],
    estimatedTime: { min: 20, max: 45 },
    skills: ['공간 인지', '관찰력', '사실적 표현', '3D 사고'],
    materials: ['연필', '자', '지우개'],
    tips: ['소실점 찾기', '가까울수록 크고 선명하게', '보조선 활용하기'],
    variations: ['1점 투시', '2점 투시', '3점 투시'],
    credits: 1
  },
  SHADING: {
    id: 'SHADING',
    name: 'Shading Practice',
    nameKo: '명암 연습',
    description: 'Learn to create depth through light and shadow',
    descriptionKo: '빛과 그림자를 표현하여 입체감을 나타냅니다',
    icon: 'Sun',
    category: 'advanced',
    difficulty: [3, 4, 5],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 15, max: 40 },
    skills: ['관찰력', '표현력', '입체 인지', '그라데이션'],
    materials: ['연필', '지우개', '블렌딩 도구', '종이'],
    tips: ['빛의 방향 먼저 정하기', '그라데이션 연습하기', '부드럽게 문지르기'],
    variations: ['기본 도형 명암', '정물 명암', '인물 명암'],
    credits: 1
  },
  TEXTURE: {
    id: 'TEXTURE',
    name: 'Texture Drawing',
    nameKo: '질감 표현',
    description: 'Learn to represent different textures through drawing',
    descriptionKo: '다양한 표면의 질감을 선과 색으로 표현합니다',
    icon: 'Brush',
    category: 'advanced',
    difficulty: [3, 4, 5],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 15, max: 35 },
    skills: ['관찰력', '표현력', '재료 이해', '다양한 선'],
    materials: ['연필', '크레파스', '다양한 도구'],
    tips: ['실제 물체를 만져보기', '다양한 선 연습하기', '도구별 특성 활용'],
    variations: ['털/모피', '나무껍질', '물/유리', '천/직물'],
    credits: 1
  },
  GESTURE: {
    id: 'GESTURE',
    name: 'Gesture Drawing',
    nameKo: '제스처 드로잉',
    description: 'Quick sketches capturing movement and essence',
    descriptionKo: '빠른 스케치로 움직임과 본질을 포착합니다',
    icon: 'Zap',
    category: 'advanced',
    difficulty: [4, 5],
    ageGroups: ['UPPER_ELEM'],
    estimatedTime: { min: 10, max: 25 },
    skills: ['빠른 관찰', '본질 파악', '자신감'],
    materials: ['연필', '크레파스', '종이'],
    tips: ['1-2분 안에 그리기', '큰 동작 먼저', '디테일은 나중에'],
    variations: ['인물 제스처', '동물 제스처'],
    credits: 1
  },
  CONTOUR: {
    id: 'CONTOUR',
    name: 'Contour Drawing',
    nameKo: '윤곽선 드로잉',
    description: 'Draw outlines while observing the subject carefully',
    descriptionKo: '대상을 관찰하며 윤곽선만으로 표현합니다',
    icon: 'Pencil',
    category: 'advanced',
    difficulty: [3, 4, 5],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 10, max: 30 },
    skills: ['관찰력', '집중력', '선 조절'],
    materials: ['연필', '펜', '종이'],
    tips: ['천천히 관찰하며 그리기', '눈과 손을 연결하기', '선을 끊지 않고 그리기 도전'],
    variations: ['블라인드 컨투어', '연속 컨투어'],
    credits: 1
  },
  NEGATIVE_SPACE: {
    id: 'NEGATIVE_SPACE',
    name: 'Negative Space',
    nameKo: '네거티브 스페이스',
    description: 'Focus on drawing the space around objects',
    descriptionKo: '물체 주변의 빈 공간을 그려 형태를 표현합니다',
    icon: 'Maximize',
    category: 'advanced',
    difficulty: [4, 5],
    ageGroups: ['UPPER_ELEM'],
    estimatedTime: { min: 15, max: 30 },
    skills: ['역발상', '공간 인식', '관찰력'],
    materials: ['연필', '마커', '종이'],
    tips: ['물체가 아닌 배경에 집중', '빈 공간의 모양 보기'],
    variations: ['손 네거티브', '정물 네거티브'],
    credits: 1
  },
  MIXED_MEDIA: {
    id: 'MIXED_MEDIA',
    name: 'Mixed Media',
    nameKo: '복합 기법',
    description: 'Combine multiple art techniques in one work',
    descriptionKo: '여러 가지 미술 기법을 조합하여 작품을 만듭니다',
    icon: 'Combine',
    category: 'special',
    difficulty: [4, 5],
    ageGroups: ['UPPER_ELEM'],
    estimatedTime: { min: 30, max: 60 },
    skills: ['종합 사고', '창의력', '계획력', '응용력'],
    materials: ['다양한 재료'],
    tips: ['어떤 기법을 조합할지 계획하기', '재료의 특성 이해하기', '단계별로 진행하기'],
    variations: ['콜라주 + 드로잉', '스탬프 + 색칠', '프로타주 + 콜라주'],
    credits: 2
  },
  COLLABORATIVE: {
    id: 'COLLABORATIVE',
    name: 'Collaborative Art',
    nameKo: '협동 작품',
    description: 'Create artwork together with multiple people',
    descriptionKo: '여러 명이 함께 하나의 작품을 완성합니다',
    icon: 'Users',
    category: 'special',
    difficulty: [2, 3, 4],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 30, max: 60 },
    skills: ['협동심', '의사소통', '존중', '창의력'],
    materials: ['큰 종이', '다양한 도구'],
    tips: ['역할 분담하기', '서로의 작업 존중하기', '함께 계획 세우기'],
    variations: ['릴레이 그리기', '퍼즐 조각', '그룹 벽화'],
    credits: 2
  },
  BOOK_MAKING: {
    id: 'BOOK_MAKING',
    name: 'Mini Book Making',
    nameKo: '미니북 만들기',
    description: 'Create small handmade books',
    descriptionKo: '나만의 작은 책을 만듭니다',
    icon: 'BookOpen',
    category: 'craft',
    difficulty: [2, 3, 4],
    ageGroups: ['LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 20, max: 45 },
    skills: ['순서 이해', '스토리텔링', '창의력'],
    materials: ['종이', '가위', '스테이플러/실'],
    tips: ['페이지 순서 확인하기', '접기 정확하게'],
    variations: ['아코디언 북', '지그재그 북', '팝업 북'],
    credits: 1
  },
  MASK: {
    id: 'MASK',
    name: 'Mask Making',
    nameKo: '가면 만들기',
    description: 'Design and create wearable masks',
    descriptionKo: '쓸 수 있는 가면을 디자인하고 만듭니다',
    icon: 'Drama',
    category: 'craft',
    difficulty: [2, 3, 4],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 20, max: 40 },
    skills: ['창의력', '디자인', '소근육'],
    materials: ['도화지', '가위', '고무줄', '색칠도구'],
    tips: ['얼굴 크기에 맞추기', '눈 위치 정확히'],
    variations: ['동물 가면', '캐릭터 가면', '전통 가면'],
    credits: 1
  },
  PUPPET: {
    id: 'PUPPET',
    name: 'Puppet Making',
    nameKo: '인형 만들기',
    description: 'Create finger or stick puppets',
    descriptionKo: '손가락 인형이나 막대 인형을 만듭니다',
    icon: 'Hand',
    category: 'craft',
    difficulty: [2, 3, 4],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 15, max: 35 },
    skills: ['창의력', '스토리텔링', '소근육'],
    materials: ['종이', '막대', '풀', '색칠도구'],
    tips: ['튼튼하게 붙이기', '움직임 고려하기'],
    variations: ['손가락 인형', '막대 인형', '그림자 인형'],
    credits: 1
  },
  FRAME: {
    id: 'FRAME',
    name: 'Frame Decorating',
    nameKo: '액자 꾸미기',
    description: 'Design and decorate picture frames',
    descriptionKo: '액자 테두리를 꾸미고 작품을 전시합니다',
    icon: 'Frame',
    category: 'craft',
    difficulty: [1, 2, 3],
    ageGroups: ['TODDLER', 'LOWER_ELEM', 'UPPER_ELEM'],
    estimatedTime: { min: 15, max: 30 },
    skills: ['디자인', '장식 감각', '창의력'],
    materials: ['두꺼운 종이', '장식 재료', '풀'],
    tips: ['중앙 공간 비워두기', '균형있게 장식하기'],
    variations: ['패턴 액자', '콜라주 액자', '자연물 액자'],
    credits: 1
  }
} as const;

export type TechniqueId = keyof typeof ART_TECHNIQUES;
export type Technique = typeof ART_TECHNIQUES[TechniqueId];

// 카테고리별 그룹핑
export const TECHNIQUE_CATEGORIES = {
  basic: { name: 'Basic', nameKo: '기초', icon: 'Pencil' },
  drawing: { name: 'Drawing', nameKo: '드로잉', icon: 'PenTool' },
  craft: { name: 'Craft', nameKo: '공예', icon: 'Scissors' },
  mixed: { name: 'Mixed', nameKo: '혼합', icon: 'Layers' },
  pattern: { name: 'Pattern', nameKo: '패턴', icon: 'Grid' },
  advanced: { name: 'Advanced', nameKo: '심화', icon: 'Star' },
  special: { name: 'Special', nameKo: '특별', icon: 'Sparkles' }
} as const;

// 기법별 프롬프트 힌트
export const TECHNIQUE_PROMPT_HINTS: Record<TechniqueId, string> = {
  COLORING: 'simple black outline drawing for coloring, clear distinct areas, clean lines',
  LINE_DRAWING: 'dotted line tracing guide, dashed lines to follow, clear path',
  DOT_CONNECT: 'numbered dots to connect, dot-to-dot puzzle, sequential numbers',
  SYMMETRY: 'half completed drawing with center line, symmetry exercise',
  MIRROR: 'mirror reflection drawing exercise, left-right reversal',
  GRID_COPY: 'grid overlay for copying, square grid reference',
  ORIGAMI: 'origami folding diagram, fold lines indicated, step markers',
  PAPER_CRAFT: 'paper craft template, cut and fold lines, assembly guide',
  CUTTING: 'cutting practice template, scissor lines, shapes to cut',
  POPUP: 'pop-up card template, fold and cut lines, 3D assembly',
  MOBILE: 'mobile hanging template, balance points marked, string attachment',
  COLLAGE: 'collage composition guide, layering areas, material suggestions',
  STENCIL: 'stencil template, cut-out areas, spray or dab zones',
  STAMP: 'stamping pattern guide, stamp placement areas',
  RUBBING: 'texture rubbing guide, rubbing zones marked',
  MARBLING: 'marbling pattern template, swirl guides',
  MOSAIC: 'mosaic grid template, small tile areas, color zones',
  MANDALA: 'mandala pattern, radial symmetry, concentric circles',
  ZENTANGLE: 'zentangle pattern template, section dividers, pattern zones',
  DOODLE: 'doodle space with minimal guides, free expression area',
  PATTERN: 'pattern repetition exercise, sequence to continue',
  BORDER: 'decorative border template, frame design area',
  PROPORTION: 'proportion guide with measurement lines, ratio reference',
  PERSPECTIVE: 'perspective drawing guide, vanishing point, horizon line',
  SHADING: 'shading practice with light source indicated, value scale',
  TEXTURE: 'texture rendering zones, different surface types',
  GESTURE: 'quick gesture drawing poses, action lines',
  CONTOUR: 'contour drawing subject, outline focus',
  NEGATIVE_SPACE: 'negative space exercise, background focus drawing',
  MIXED_MEDIA: 'mixed media template, multiple technique zones',
  COLLABORATIVE: 'collaborative art sections, divided areas for multiple artists',
  BOOK_MAKING: 'mini book template, page layout, fold lines',
  MASK: 'mask template, face outline, eye and mouth holes',
  PUPPET: 'puppet template, movable parts, attachment points',
  FRAME: 'frame decorating template, border design area'
};

// 기법을 카테고리별로 그룹화하는 헬퍼 함수
export function getTechniquesByCategory(category: string): TechniqueId[] {
  return Object.entries(ART_TECHNIQUES)
    .filter(([_, technique]) => technique.category === category)
    .map(([id]) => id as TechniqueId);
}

// 연령대별 추천 기법 가져오기
export function getTechniquesForAgeGroup(ageGroup: string): TechniqueId[] {
  return Object.entries(ART_TECHNIQUES)
    .filter(([_, technique]) => (technique.ageGroups as readonly string[]).includes(ageGroup))
    .map(([id]) => id as TechniqueId);
}
